# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='relates_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='friends_app.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
