# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_auto_20180429_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relates_to',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='faves', to='friends_app.User'),
        ),
    ]
